/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Handle skip waiting message from the app
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Accepted image types (can't import from lib/types.ts in service worker)
const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];

// IndexedDB helper for storing shared files
const DB_NAME = "param-img-share";
const STORE_NAME = "shared-files";

async function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, 1);
    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);
    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME);
      }
    };
  });
}

async function storeSharedFiles(files: Array<File>): Promise<void> {
  const db = await openDB();
  const tx = db.transaction(STORE_NAME, "readwrite");
  const store = tx.objectStore(STORE_NAME);

  // Clear previous shared files
  store.clear();

  // Store new files
  for (let i = 0; i < files.length; i++) {
    store.put(files[i], `file-${i}`);
  }

  return new Promise((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

// Handle share target POST requests
self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);

  // Only handle POST requests to /_share
  if (url.pathname === "/_share" && event.request.method === "POST") {
    event.respondWith(handleShareTarget(event.request));
  }
});

async function handleShareTarget(request: Request): Promise<Response> {
  try {
    const formData = await request.formData();
    const files: Array<File> = [];

    // Get all shared images (validate against accepted types)
    const images = formData.getAll("images");
    for (const image of images) {
      if (image instanceof File && ACCEPTED_IMAGE_TYPES.includes(image.type)) {
        files.push(image);
      }
    }

    if (files.length > 0) {
      // Store files in IndexedDB for the app to retrieve
      await storeSharedFiles(files);
    }

    // Redirect to the app with a flag indicating shared content
    return Response.redirect("/?shared=true", 303);
  } catch (error) {
    console.error("Error handling share target:", error);
    return Response.redirect("/", 303);
  }
}
